
import javax.swing.JOptionPane;


public class Jfuncion extends javax.swing.JFrame {

    /**
     * Creates new form Jfuncion
     */
    public Jfuncion() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        BtnSalir = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnMulti = new javax.swing.JButton();
        BtnSuma1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FUNCION DE SUMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 70, 50));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 70, 50));

        BtnSalir.setBackground(new java.awt.Color(204, 204, 204));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnSalir.setText("SALIR");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        BtnResta.setBackground(new java.awt.Color(204, 204, 204));
        BtnResta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BtnResta.setText("-");
        BtnResta.setBorderPainted(false);
        BtnResta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, 50));

        BtnMulti.setBackground(new java.awt.Color(204, 204, 204));
        BtnMulti.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BtnMulti.setText("*");
        BtnMulti.setBorderPainted(false);
        BtnMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, 50));

        BtnSuma1.setBackground(new java.awt.Color(204, 204, 204));
        BtnSuma1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BtnSuma1.setText("+");
        BtnSuma1.setBorderPainted(false);
        BtnSuma1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuma1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 102, 60, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/wallpaper1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        // TODO add your handling code here:
        int resultado,a,b;
        a=Integer.parseInt(jTextField1.getText());
        b=Integer.parseInt(jTextField2.getText());
        resultado=resta(a, b);
        JOptionPane.showMessageDialog(null,"El resultado es: " + resultado); 
    }//GEN-LAST:event_BtnRestaActionPerformed

    private void BtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiActionPerformed
        // TODO add your handling code here:
        int resultado,a,b;
        a=Integer.parseInt(jTextField1.getText());
        b=Integer.parseInt(jTextField2.getText());
        resultado=multi(a, b);
        JOptionPane.showMessageDialog(null,"El resultado es: " + resultado); 
    }//GEN-LAST:event_BtnMultiActionPerformed

    private void BtnSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuma1ActionPerformed
        // TODO add your handling code here:
        int resultado,a,b;
        a=Integer.parseInt(jTextField1.getText());
        b=Integer.parseInt(jTextField2.getText());
        resultado=suma(a, b);
        JOptionPane.showMessageDialog(null,"El resultado es: " + resultado); 
    }//GEN-LAST:event_BtnSuma1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new Jfuncion().setVisible(true);
            }
        });
     
    }

  static int suma(int a, int b){
        return a+b;
    }
  static int resta(int a, int b){
        return a-b;
    }
  static int multi(int a, int b){
        return a*b;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMulti;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSuma1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
